import time
print("\033[1;34;1m            ID form \n")
print("******************************")
print("")
time.sleep(2)

print("\033[1;37;1mWhat is your first name?")
firstname = input()
print("")
print("")
time.sleep(1)
print("What is your surname?")
surname = input()
print("")
print("\033[1;32;1m Hello", firstname,surname, "!")
print("")
print("")
time.sleep(1)
print("\033[1;37;1mWhat is your age?")
age = input()
print("")
print("")
time.sleep(1)
print("What is your address?")
address = input()
print("")
print("")
time.sleep(1)
print("What is your email?")
email = input()
print("")
print("")
time.sleep(1)
print("What is your number?")
num = input()
print("")
print("\033[1;34;1m********************************************")
time.sleep(2.5)
print("Thank you for completing the ID form")
print("")
print("")
print("\033[1;34;1mName:", firstname,surname)
print("Age:", age)
print("Address", address)
print("Email:", email)
print("Number:", num)