import time
print("\033[1;34;1m            ID form \n")
print("******************************")
print("")
time.sleep(2)

print("\033[1;37;1mWhat is your first name?")
firstname = input()
print("")
print("")
time.sleep(1)
print("What is your surname?")
surname = input()
print("")
print("\033[1;32;1mHello", firstname,surname, "!")
print("")
print("")
time.sleep(1)
print("Your initials are:",firstname[0],surname[0])
print("")
time.sleep(1)
fullname = firstname +" "+ surname
print("Your fullname is " + fullname)
print("")
time.sleep(1)
print("Your firstname in uppercase is", firstname.upper())
print("")
time.sleep(1)
print("Your firstname is",str(len(firstname)),"letter(s) long")
print("")
print("")
time.sleep(1)
sure = surname.lower()
fire = firstname.lower()
sur = str(len(surname))
print("\033[1;34;1m Your username is " + sure[0] + sure[1] + sure[2] + fire[0] + sur)