# -*- coding: utf-8 -*-
"""Data Frames of Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y0izZC2xP4MGi6Qv46BqZzZ3lxZ7-RP7
"""

import pandas as pd
student=['Rick','Bob','Micky','John']
s1 = pd.Series(student)

print(s1)
print(type(s1))

import pandas as pd
student = [['Rick', 'Bob'], ['Micky','John']]
s1 = pd.Series(student)

print(s1)
print(type(s1))

"""Pandas Series from a dictionary"""

d1 ={'column1':['Name', 'Grade', 'Sex']}
print(d1)
print(type(d1))

df1 = pd.Series(d1)
print(df1)
print(type(df1))
df1

d1 ={'column1':['Name', 'Grade', 'Sex'], 'column2':['Rick', 5, "Male"]}
print(d1)
print(type(d1))

df1 = pd.Series(d1)
print(df1)
print()
print(type(df1))

df1

student = ['Rick', 5, "Male"]

df = pd.DataFrame(student)

df

student = [['Rick', 5, "Male"]]

df = pd.DataFrame(student)

df

import pandas as pd

student = [['Rick', 5, "Male"],
           ['Bob', 7, "Male"],
           ['Micky', 8, "Female"],
           ['John', 3, "Male"]]

df = pd.DataFrame(student)

print(type(df))

df

import pandas as pd

student = [['Rick', 5, "Male"],
           ['Bob', 7, "Male"],
           ['Micky', 8, "Female"],
           ['John', 3, "Male"]]

df = pd.DataFrame(student, columns=['Name', 'Grade', 'Sex'])

df

d1 = {'column1':['Name', 'Grade', 'Sex']}
print(d1)
print(type(d1))

df1 = pd.DataFrame(d1)
print(df1)
print(type(df1))

df1

d1 = {'column1':['Name', 'Grade', 'Sex'], 'column2':['Rick', 5, "Male"],'column3':['Bob', 7, "Male"], 'column4': ['Micky', 8, "Female"],'column5': ['John', 3, "Male"]}
print(d1)
print(type(d1))

df1 = pd.DataFrame(d1)
print(df1)
print()
print(type(df1))

df1

d1={'Name':['Rick','Bon','Micky','John'], 'Grade':[5,7,8,3], 'Sex':["Male", "Male", "Female","Male"]}
print(d1)
print(type(d1))

df1 = pd.DataFrame(d1)

print(type(df1))
print()
df1

d1={'Name':['Rick','Bob','Micky','John'],
    'Grade':[5,7,8,3],
    'Sex':["Male", "Male","Female","Male"]}

df1 = pd.DataFrame(d1, index = ["a","b","c","d"])

df1

month= ['January', 'February', 'March', 'April', 'May', 'June']
sale = [15000, 18000, 20500, 22000, 19500, 25000]
d3={"months": month,"sales":sale}
print(d3)

import pandas as pd
df3 = pd.DataFrame(d3, index=list(range(1,7)))

df3

df1.columns

df1.dtypes

print(type(df1['Name']))
print()
df1['Name']

print(type(df1[['Name','Sex']]))
print()
df1[['Name','Sex']]

print(df1.loc['c'])
print()
print(type(df1.loc['c']))

print(df1.loc[['c','d']])
print()
print(type(df1.loc[['c','d']]))

df1

df1.loc['b','Grade']

print(df1.loc[:,'Name'])
print()
print(type(df1.loc[:,'Name']))

print(df1.loc[['b','c'],['Name','Grade']])
print()
print(type(df1.loc[:,'Name']))

print(df1.iloc[0])
print()
print(type(df1.iloc[0]))

print(df1.iloc[:,0])
print()
print(type(df1.iloc[:,0]))

print(df1.iloc[[1,2]])
print()
print(type(df1.iloc[[1,2]]))

print(df1.iloc[[1,2],[0,1]])
print()
print(type(df1.iloc[[1,2],[0,1]]))