# -*- coding: utf-8 -*-
"""Intro to Data Visualisation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tLZ4Ju-6aBgbp1dx-i7JN0RihENLXpB8
"""

x=list(range(1,6))
print(x)

y=list(range(5,26,5))
print(y)

# import matplotlib pyplot as plt alias:
import matplotlib.pyplot as plt
# setting the size of display figure
plt.figure(figsize=(5,2))
# for ploting bar graph
plt.bar(x,y)

# import matplotlib pyplot as plt alias:
import matplotlib.pyplot as plt
# setting the size of display figure
plt.figure(figsize=(5,2))
# Add labels and title
plt.xlabel("this is my x axis")
plt.ylabel("this is my y axis")
plt.title("this is my x vs y")
# for ploting bar graph
plt.bar(x,y)

Activities	=['School','Study','Play',	'Sleep','Others']
Time_spent =[6, 4, 1.5, 8, 4.5]
import matplotlib.pyplot as plt
plt.figure(figsize=(6,4))
# Add labels and title
plt.xlabel('Activities')
plt.ylabel('Time spent (in hrs)')
plt.title('Time spent by a child during a day')
# for ploting bar graph
plt.bar(Activities,Time_spent)

'''Raw Data:

January: $15,000
February: $18,000
March: $20,500
April: $22,000
May: $19,500
June: $25,000
July: $28,000
August: $24,500
September: $23,000
October: $26,000
November: $30,000
December: $32,500'''


import matplotlib.pyplot as plt

# Sample data
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
sales = [15000, 18000, 20500, 22000, 19500, 25000, 28000, 24500, 23000, 26000, 30000, 32500]

# Create a line plot
plt.bar(months, sales, color='#ee82ee')

# Add labels and title
plt.xlabel('Months')
plt.ylabel('Sales Amount ($)')
plt.title('Monthly Sales Data')

# for seting x lables vertical
plt.xticks(range(len(months)), months, rotation='vertical')

# Rotate the x-axis labels for better readability
#plt.xticks(rotation=45)

# Display the plot
plt.show()

import matplotlib.pyplot as plt

# Sample data
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
sales = [15000, 18000, 20500, 22000, 19500, 25000, 28000, 24500, 23000, 26000, 30000, 32500]

# Create a line plot
plt.plot(months, sales, marker='o', color='#ee82ee')

# Add labels and title
plt.xlabel('Months')
plt.ylabel('Sales Amount ($)')
plt.title('Monthly Sales Data')

# for setting x label vertical
plt.xticks(rotation=90)

# Display the plot
plt.show()

"""Student's activities"""

import matplotlib.pyplot as plt

categories = ['Housing', 'Utilities', 'Transportation', 'Groceries', 'Entertainment', 'Healthcare', 'Education', 'Miscellaneous']
expenses = [1200, 300, 400, 500, 200, 150, 250, 100]

# Create a bar graph
plt.bar(categories, expenses, color='blue')

# Add labels and title
plt.xlabel('Categories')
plt.ylabel('Amount (USD)')
plt.title('Monthly Expenses of a Household')
#plt.title('Monthly Expenses of a Household \n This bar graph will visually represent the monthly expenses for each category,\n making it easy to compare and understand the distribution of expenditures within the household.')

# Rotate the x-axis labels for better readability
plt.xticks(rotation=45)

# Display the plot
plt.tight_layout()  # To avoid overlapping labels
plt.show()
#This bar graph will visually represent the monthly expenses for each category,
#making it easy to compare and understand the distribution of expenditures within the household.