# -*- coding: utf-8 -*-
"""Intro to Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P-7Zyp2MLOIa7rVziwreJ7Onn0JKIZkW
"""

# X-a-thon grocery store
import time
Name = input("What is your name?")
print("")
time.sleep(0.12)
print("Loading...")
time.sleep(2)
print("")
print("Hi, " + Name + "!")
print("")
time.sleep(2)
print("Hello, {} welcome to X-a-thon gorcery store!".format(Name))
print("")
time.sleep(3)
print("Press 1 to shop for food!")
print("")
time.sleep(2)
print("Press 2 to shop for furniture!")
print("")
time.sleep(2)
print("Press 3 to shop for Apple devices!")
print("")
time.sleep(2)
print("Press 4 to shop for stationary supplies!")
print("")
time.sleep(2)
print("Press 5 to shop for Lego sets!")
print("")
time.sleep(1)
Choice = input()
print("Ok, let me conntact your intrested department")
print("")
print("Loading...")
print("")
time.sleep(2)
print("Done, our website will open on a new window with your desired things")

# Are you old?
import time
Name = input("What's your name?")
time.sleep(1)
print("")
print("So, one more thing")
print("")
Age = input("What's your age?")
print("")
time.sleep(1)
#print("Hi, " + Name + "!" + " Wait...you're " + Age + "!" + "That's soo old!")
print("Hi,  {}! Wait...you're {}! That's soo old!".format(Name, Age))

# Digit Finder
import time
A = input("What number do you want?")
if A >= 10:
    time.sleep(1)
    print("Your number is or is more than 2 digits!")
else:
    time.sleep(1)
    print("Your number is 1 digit!")

# Greater number finder
import time
print("Type 2 numbers, I will find out which one is greater!")
time.sleep(2)
print("")
First_number = int(input("What is your first number?"))
time.sleep(1)
print("")
print("ok...")
print("")
Second_number = int(input("What is your second number?"))
time.sleep(1)
print("")
print("ok...")
print("")
time.sleep(2)
print("Loading...")
print("")
time.sleep(4)
if First_number > Second_number:
  print(str(First_number)  + " is greater!")
elif First_number == Second_number:
  print("Hey, they both are the same number !")
else:
  print(str(Second_number) + " is greater!")

# Driving car allowance
import time
print("Car allowance test!")
print("")
#Answer = input("Do you dirve a car with no-one's help?")
#print("")
#if Answer == "No" or "no":
  #print("OK, bye this test is not for you...")

#else Answer == "Yes" or "yes":
  print("Ok let's start")
  print("")
  time.sleep(2)
  Age = int(input("How old are you?"))
  time.sleep(1)
  print("")
  if Age < 18:
    print("Oh, No... You're to young to drive a car!")
    time.sleep(1)
    print("")
    print("Your illegal!")
    else:
      print("Great, you're the right age to be driving a car!")

# Data types
import time
#Intiger = 4
#print(type(A))
#Float = 4.8
#print(type(B))
#String = "Hi"
#print(type(C))
#Tuple = ("Hi", "person")
#print(type(D))
#Dictionary = {"Name": "What a person is called"}
#print(type(E))
Name = input("What's your name?")
#print(type(Name))
print("")
print("Hi...welcome, " + Name + "!")
time.sleep(1)
print("")
Age = float(input("How old are you?"))
time.sleep(1)
print("")
#print(type(Age))
if Age > 5:
  #print("Ok, " + Name + ". "  + "You're old enough to drive an e-scooter!")
  print("Ok, {}. You're {}, that's old enough to drive an e-scooter".format(Name, Age))
else:
  #print("Sorry, " + Name + ". " + "You're to young to drive an e-scooter")
  print("Sorry, {}. You're to young to drive an e-scooter. You have to be over {}".format(Name, Age))

# Calculator
import time
Answer = 0
Number1 = int(input("What is your first number?"))
time.sleep(1)
print("")
Operation = input("What is your operation? (+, -, × and ÷)")
time.sleep(1)
print("")
Number2 = int(input("What's your second number?"))
time.sleep
print("")
if Operation == "+" :
  print("The answer is...")
  time.sleep(2)
  print("")
  Answer = str((Number1 + Number2))
  print("{} {} {} = {}".format(Number1, Operation, Number2, Answer))
  #print(Answer + "!")
elif Operation == "-":
    print("The answer is...")
    time.sleep(2)
    print("")
    Answer = str((Number1 - Number2))
    print("{} {} {} = {}".format(Number1, Operation, Number2, Answer))
    #print(Answer + "!")
elif Operation == "÷":
    print("The answer is...")
    time.sleep(2)
    print("")
    Answer = str((Number1 / Number2))
    print("{} {} {} = {}".format(Number1, Operation, Number2, Answer))
   # print(Answer + "!")
elif Operation == "×":
  print("The answer is...")
  time.sleep(2)
  print("")
  Answer = str((Number1 * Number2))
  print("{} {} {} = {}".format(Number1, Operation, Number2, Answer))
  #print(Answer + "!")
else:
  print("What!.. you typed the wrong stuff, NOW PERISHH!")
  time.sleep(1)
  print("")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")

# Conditions
import time
print("Hi, welcome to World Tour Bot.")
time.sleep(1)
print("")
print("Press 1 if you want to go to Asia")
print("")
time.sleep(2)
print("Press 2 if you want to go to Europe")
print("")
Choice = input()
print("")
if (Choice == "1"):
  Country = input("Which country do you want to visit, ( Russia, Bangladesh or U.A.E)")
  print("")
  time.sleep(2)
  if (Country == "Russia"):
    print("Welcome,... to the biggest country in the WORLD!")
  elif (Country == "Bangladesh"):
    print("Welcome,... to the country that won war without wepons or military force!")
  elif (Country == "U.A.E"):
    print("Welcome,... to one of the fastest growing countries in the world!")
  else:
    print("Please enter one of these countries, ( Russia, Bangladesh or U.A.E)")
elif (Choice == "2"):
  Country = input("Which country do you want to visit, ( England, Switzerland or Poland)")
  print("")
  time.sleep(2)
  if (Country == "England"):
    print("Welcome to the country that most of the world's scientist were born!")
  elif (Country == "Switzerland"):
    print("Welcome to the country of FOOD!")
  elif (Country == "Poland"):
    print("Welcome to the 9th largest country in Europe!")
  else:
    print("Please enter on of these countries, ( England, Switzerland or Poland)")
else:
    print("Please enter the correct input")

#NUMBERS
import time
Numbers = 0
print("Answer the following question in lowercase.")
print("")
time.sleep(1)
Yes = input("Do you know all the numbers in the world?")
print("")
if Yes == "yes":
  print("Ohh, your smart...!")
else:
  print("Ok, here you are!")
  time.sleep(2)
  print("")
  while True:
    print(Numbers)
    print("")
    time.sleep(1)
    Numbers = Numbers + 1

# Pattern printing (Hard) 1
Number = int(input("Choose any number!"))
Star = "^"
for i in range (0,Number):
  for p in range (0,i + 1):
    print(Star, end = "")
  print("\r")

# Pattern printing (Easy) 1
for i in range (1,10):
  print("#" * i)

# Pattern printing (Easy) 2
for i in range (1,10):
  print("1" * i)

# Pattern printing (Hard) 2
N = ""
for i in range (1,10):
  N = N+str(i)
  print(N)

# Pattern printing (Hard) 3
N = ""
for i in range (1,10,2):
  N = N+str(i)
  print(N)

# Times table
import time
Number = int(input("Choose a number"))
End = int(input("Choose a second number"))
for i in range (1,End + 1):
  Answer = (Number * i)
  print("{} × {} = {}".format(Number, i, Answer))
  print("")

# Circle (Slow version)
!pip3 install ColabTurtle
import ColabTurtle.Turtle as t
t.initializeTurtle()
for i in range (360):
  t.forward(1)
  t.right(1)

# Square
!pip3 install ColabTurtle
import ColabTurtle.Turtle as t
t.initializeTurtle()
for i in range (4):
  t.forward(100)
  t.right(90)

# Triangle
!pip3 install ColabTurtle
import ColabTurtle.Turtle as t
t.initializeTurtle()
Back = input("What color should be your backgorund?")
Pen = input("What color should be your turtle?")
t.bgcolor(Back)
t.pencolor(Pen)
for i in range (3):
   t.forward(100)
   t.right(120)
t.left(180)
for p in range (3):
 t.right(120)
 t.forward(100)
t.penup()
t.forward(100)
t.left(180)
t.pendown()
for i in range (3):
   t.forward(100)
   t.right(120)
t.left(180)
for p in range (3):
 t.right(120)
 t.forward(100)
t.penup()
t.left(180)
t.forward(100)
t.left(90)
t.forward(100)
t.pendown()
for i in range (3):
   t.forward(100)
   t.right(120)
t.left(180)
for p in range (3):
 t.right(120)
 t.forward(100)
t.penup()
t.forward(200)
for i in range (3):
   t.forward(100)
   t.right(120)
t.left(180)
for p in range (3):
 t.right(120)
 t.forward(100)

# Input shapes
import time
print("Type a number and see it's shape!")
print("")
time.sleep(2)
Background = input("What should be the background")
print("")
time.sleep(1)
Pen_color = input("What should be the pen color")
print("")
time.sleep(1)
Answer = int(input("Which number do you want?"))
print("")
time.sleep(1)
Degree = 360 / Answer
!pip3 install ColabTurtle
import ColabTurtle.Turtle as t
t.initializeTurtle()
t.bgcolor(Background)
t.pencolor(Pen_color)
for i in range (Answer):
  t.forward(100)
  t.right(Degree)

# Squares and more squares...WITH MORE SQUARES!!
import time
Background = input("What color should be the background")
print("")
time.sleep(1)
Pen_color = input("What should be the pen color")
print("")
time.sleep(1)
Width = int(input("What should be the thickness?"))
print("")
time.sleep(1)
!pip3 install ColabTurtle
import ColabTurtle.Turtle as t
t.initializeTurtle()
t.bgcolor(Background)
t.pencolor(Pen_color)
t.width(Width)
for i in range (4):
  t.forward(100)
  t.right(90)
t.penup()
t.left(90)
t.forward(20)
t.right(90)
t.pendown()
for i in range (4):
  t.forward(100)
  t.left(90)
t.penup()
t.left(90)
t.forward(120)
t.pendown()
for i in range (4):
  t.forward(100)
  t.right(90)
t.penup()
t.forward(120)
t.pendown()
for i in range (4):
  t.forward(100)
  t.right(90)
t.penup()
t.left(180)
t.forward(380)
t.pendown()
for i in range (4):
  t.forward(100)
  t.left(90)
t.penup()
t.forward(120)
t.left(90)
t.pendown()
for i in range (4):
  t.forward(100)
  t.right(90)
t.penup()
t.left(90)
t.forward(240)
t.left(90)
t.forward(130)
t.left(180)
t.pendown()
for i in range (4):
  t.forward(100)
  t.right(90)
t.penup()
t.left(90)
t.forward(20)
t.right(90)
t.pendown()
for i in range (4):
  t.forward(100)
  t.left(90)
t.penup()
t.left(90)
t.forward(120)
t.pendown()
for i in range (4):
  t.forward(100)
  t.right(90)
t.penup()
t.forward(120)
t.pendown()
for i in range (4):
  t.forward(100)
  t.right(90)
t.penup()
t.left(180)
t.forward(380)
t.pendown()
for i in range (4):
  t.forward(100)
  t.left(90)
t.penup()
t.forward(120)
t.left(90)
t.pendown()
for i in range (4):
  t.forward(100)
  t.right(90)

# Triangle and more triangle...WITH MORE TRIANGLES!!
import time
Background = input("What color should be the background")
print("")
time.sleep(1)
Pen_color = input("What should be the pen color")
print("")
time.sleep(1)
Width = int(input("What should be the thickness?"))
print("")
time.sleep(2)
!pip3 install ColabTurtle
import ColabTurtle.Turtle as t
t.initializeTurtle()
t.bgcolor(Background)
t.pencolor(Pen_color)
t.width(Width)
for i in range (3):
  t.forward(100)
  t.right(120)
t.penup()
t.left(90)
t.forward(20)
t.right(90)
t.pendown()
for i in range (3):
  t.forward(100)
  t.right(120)
t.penup()
t.left(90)
t.forward(120)
t.pendown()
for i in range (3):
  t.forward(100)
  t.right(120)
t.penup()
t.forward(120)
t.pendown()
for i in range (3):
  t.forward(100)
  t.right(120)
t.penup()
t.left(180)
t.forward(380)
t.pendown()
for i in range (3):
  t.forward(100)
  t.right(120)
t.penup()
t.forward(120)
t.left(90)
t.pendown()
for i in range (3):
  t.forward(100)
  t.right(120)
t.penup()
t.left(90)
t.forward(240)
t.left(90)
t.forward(130)
t.left(180)
t.pendown()
for i in range (3):
  t.forward(100)
  t.right(120)
t.penup()
t.left(90)
t.forward(20)
t.right(90)
t.pendown()
for i in range (3):
  t.forward(100)
  t.right(120)
t.penup()
t.left(90)
t.forward(120)
t.pendown()
for i in range (3):
  t.forward(100)
  t.right(120)
t.penup()
t.forward(120)
t.pendown()
for i in range (3):
  t.forward(100)
  t.right(120)
t.penup()
t.left(180)
t.forward(380)
t.pendown()
for i in range (3):
  t.forward(100)
  t.right(120)
t.penup()
t.forward(120)
t.left(90)
t.pendown()
for i in range (3):
  t.forward(100)
  t.right(120)

# Fun - ctions 1
import time
def Greeting(a):
  print("")
  print("Hello, " +a)
  time.sleep(2)
  print("")
  Feeling = input("How are you?")
Greeting(input("What's your name?"))

# Fun-ctions 2
import time
Length = int(input("What is the length of your object?"))
print("")
time.sleep(2)
Width = int(input("What is the width of your object?"))
def Area():
  print("")
  time.sleep(1)
  Answer = Length * Width
  print("The area of your object is... {}!".format(Answer))
Area()
print("")
time.sleep(2)
print("Now, it's time to find the perimeter of your shape (circles don't count)")
def Perimeter():
  print("")
  time.sleep(2)
  Answer2 =  Length + Width
  Answer3 = 2 * Answer2
  print("The perimeter of your shape is... {}!".format(Answer3))
Perimeter()

# FUNCTIONS with IF command!!!!
import time
Length = int(input("What is the length of your object?"))
print("")
time.sleep(2)
Width = int(input("What is the width of your object?"))
print("")
time.sleep(1.16)
def Area():
  print("")
  time.sleep(1)
  Answer = Length * Width
  print("The area of your object is... {}!".format(Answer))
def Perimeter():
  print("")
  time.sleep(2)
  Answer2 =  Length + Width
  Answer3 = 2 * Answer2
  print("The perimeter of your shape is... {}!".format(Answer3))
Result = input("Do you want the perimeter of your shape or the area?(all lowercase)")
if Result == "perimeter":
  Perimeter()
elif Result == "area":
  Area()
else:
  print("That was not an option soo...")
  time.sleep(2)
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")
  print("EROR...ERORR!!!")

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
                                                                             Advanced projects below!!

# Factrorial numbers
Fact = int(input("What is your number?"))
N = 1
for i in range (1, Fact + 1):
  N = (N * i)
print(N)

# Odd or Even
Number = int(input("What's your number? "))
print("")
if Number % 2 == 0:
  print("Your number is even!")
else:
  print("Your number is odd!")

# Multiplication table
import time
Table = int(input("Which times table do you want?"))
print("")
time.sleep(1)
End = int(input("Tell me the number by which the table should be executed"))
End = End + 1
for i in range (1, End):
  print("{} × {} = {}".format(Table, i, Table * i))
  print("")
  time.sleep(0.16)

# Prime number checker
import time
Prime = int(input("What number do you want?"))
print("")
time.sleep(1)
for i in range (2, Prime):
  if Prime % i == 0:
    print("It's not a prime number!")
    break
  else:
    print("It's a prime number!")
    break

# Datetime
import datetime
Y = datetime.datetime.now()
print(Y)

# Math module 1
import math
Y = math.sqrt(432)
print(Y)
# sqrt(square root) is squared like 432 squared

# Maths module 2
import math as m
Y = m.ceil(4.3)
print(Y)
# ceil(ceiling) rounds decimal number up

# Maths module 2
import math as m
Y = m.floor(24.999)
print(Y)
# floor rounds decimal number down
